Repository mousamdhakal/floral-exchange, pull requests merged in 2021-11, with the labels that each got.

#1 Added new model and api route for post
  server/package-lock.json
  server/package.json
  server/src/controllers/post.js
  server/src/controllers/user.js
  server/src/middlewares/authenticate.js
  server/src/middlewares/validators/post.js
  server/src/models/Post.js
  server/src/models/User.js
  server/src/routes.js
  server/src/routes/post.js
  server/src/services/post.js
Labels: api

#2 Fe 4 add signin
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/userActions.js
  client/src/containers/root.js
  client/src/index.js
  client/src/reducers/userReducers.js
  client/src/routes.js
  client/src/sagas/index.js
  client/src/services/http.js
  client/src/styles/index.scss
  client/src/utils/authorizationHeader.js
  client/src/utils/constants.js
  client/src/views/login/Login.js
Labels: frontend

#3 Fe 6 dashboard
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/uiActions.js
  client/src/actions/userActions.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.scss
  client/src/components/NavButton/NavButton.js
  client/src/components/NavButton/NavButton.scss
  client/src/hoc/withAuthenticated.js
  client/src/hoc/withUnAuthenticated.js
  client/src/reducers/index.js
  client/src/reducers/uiReducers.js
  client/src/reducers/userReducers.js
  client/src/routes.js
  client/src/sagas/index.js
  client/src/sagas/userSagas.js
  client/src/styles/global.css
  client/src/styles/index.scss
  client/src/views/Activity/Activity.js
  client/src/views/Chats/Chats.js
  client/src/views/DashBoard/DashBoard.js
  client/src/views/DashBoard/DashBoard.scss
  client/src/views/NewItem/NewItem.js
  client/src/views/Profile/Profile.js
  client/src/views/login/Login.js
  server/src/controllers/user.js
Labels: frontend, api
